version: '3'

services:
  frontend:
    build: ./frontend
    ports:
      - 80:8080
    depends_on:
      - backend
    networks:
      - web
    volumes:
      - ./settings.json:/settings.json:ro

  backend:
    build: ./backend
    ports:
      - 51820:51820/udp
    cap_add:
      - NET_ADMIN
    depends_on:
      - redis
    networks:
      - redis
      - web
    volumes:
      - ./settings.json:/settings.json:ro

  redis:
    image: "redis:alpine"
    expose:
      - 6379
    command: ["redis-server", "--appendonly", "yes"]
    volumes:
      - /data
    networks:
      - redis

networks:
  redis:
    driver: bridge
  web:
    driver: bridge
