version: '3'

services:
  frontend:
    build: ./frontend
    ports:
      - 80:8080
    depends_on:
      - backend
    networks:
      - web
    environment:
      - OIDC_DISCOVERY_URL=${OIDC_DISCOVERY_URL}
      - OIDC_CLIENT_ID=${OIDC_CLIENT_ID}
      - OIDC_CLIENT_SECRET=${OIDC_CLIENT_SECRET}
      - EMAIL_DOMAIN=${EMAIL_DOMAIN}
      - HTTP_SERVER_NAME=${HTTP_SERVER_NAME}

  backend:
    build: ./backend
    ports:
      - ${WG_SERVER_PORT}:${WG_SERVER_PORT}/udp
    cap_add:
      - NET_ADMIN
    depends_on:
      - redis
    networks:
      - redis
      - web
    environment:
      - WG_SERVER_INTERFACE=${WG_SERVER_INTERFACE}
      - WG_SERVER_CIDR=${WG_SERVER_CIDR}
      - WG_SERVER_ENDPOINT=${WG_SERVER_ENDPOINT}
      - WG_SERVER_PORT=${WG_SERVER_PORT}
      - WG_DNS=${WG_DNS}
      - WG_ALLOWED_IPS=${WG_ALLOWED_IPS}

  redis:
    image: "redis:alpine"
    expose:
      - 6379
    command: ["redis-server", "--appendonly", "yes"]
    volumes:
      - /data
    networks:
      - redis

networks:
  redis:
    driver: bridge
  web:
    driver: bridge
