version: '3'

services:
  proxy:
    build: ./proxy
    ports:
      - 80:8080
      - 443:443
    depends_on:
      - api
    networks:
      - web
    volumes:
      - ./ssl:/ssl:ro
      - ./settings.json:/settings.json:ro

  api:
    build: ./api
    expose:
      - 8080
      - 8081
    environment:
      - LOCAL=true
      - MQ_REDIS_SERVER_ADDRESS=redis:6379
      - MQ_REDIS_SERVER_PASSWORD=pass
      - MQ_CHANNELS=wg0,wg1
    cap_add:
      - NET_ADMIN
    depends_on:
      - redis
    networks:
      - redis
      - web
      - wss
    volumes:
      - ./settings.json:/settings.json.tpl:ro

  wss0:
    build: ./wss
    ports:
      - 51820:51820/udp
    environment:
      - WG_INTERFACE=wg0
      - WG_NETWORK=10.100.1.1/24
      - WG_PORT=51820
    cap_add:
      - NET_ADMIN
    depends_on:
      - api
    networks:
      - wss

  wss1:
    ports:
      - 51821:51821/udp
    environment:
      - WG_INTERFACE=wg1
      - WG_NETWORK=10.100.0.1/24
      - WG_PORT=51821
    build: ./wss
    cap_add:
      - NET_ADMIN
    depends_on:
      - api
    networks:
      - wss

  redis:
    image: "redis:alpine"
    expose:
      - 6379
    command: ["redis-server", "--appendonly", "yes", "--requirepass", "pass"]
    volumes:
      - /data
    networks:
      - redis

networks:
  redis:
    driver: bridge
  web:
    driver: bridge
  wss:
    driver: bridge
