version: '3'

services:
  proxy:
    build: ./proxy
    ports:
      - 80:8080
      - 443:443
    depends_on:
      - api
    networks:
      - web
    volumes:
      - ./ssl:/ssl:ro
      - ./settings.json:/settings.json:ro

  api:
    build: ./api
    ports:
      - 51820:51820/udp
      - 8080:8080/tcp
    environment:
      - LOCAL=true
      - MQ_REDIS_SERVER_ADDRESS=redis:6379
      - MQ_REDIS_SERVER_PASSWORD=pass
      - MQ_CHANNELS=peers
    cap_add:
      - NET_ADMIN
    depends_on:
      - redis
    networks:
      - redis
      - web
    volumes:
      - ./settings.json:/settings.json.tpl:ro

  redis:
    image: "redis:alpine"
    expose:
      - 6379
    command: ["redis-server", "--appendonly", "yes", "--requirepass", "pass"]
    volumes:
      - /data
    networks:
      - redis

networks:
  redis:
    driver: bridge
  web:
    driver: bridge
